image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release

test_job:
  stage: test
  script:
    - dotnet test --no-restore --verbosity normal
